### ISSUE TITLE
you're breaking my copyright

### ISSUE THREAD

**Issue by DaMatrix** [2F4Uof2b2t/SashaProxy#1]
Read https://github.com/DaMatrix/Pork2b2tBot/blob/master/LICENSE

You're not allowed to release this under GPL3, and you're not linking to the original repository. I **will** make a DMCA if this isn't changed.

**Comment by 2F4Uof2b2t** [comment]
Fixed. So sorry about that. I'm bad :(

**Comment by DaMatrix** [comment]
Quick question: why not just fork mine? It'd be easier for both of us (I only found this repo because somebody was telling me that you made a proxy too and then I googled around, I would have found it faster if you'd forked it :P)

**Comment by 2F4Uof2b2t** [comment]
I used to have it forked but I was dumb and did some stupid stuff to my computer and had to redo all my repos and it was really annoying.

Maybe if I get the time to be active on the project again I'll refork

**Comment by DaMatrix** [comment]
Whatever ¯\\\_(ツ)\_/¯ I just don't really see the advantage in this project and what exactly you're doing here that's different from mine (aside from manually adding dependencies to source).

**Comment by 2F4Uof2b2t** [comment]
I don't have a lot of time to work on it anyways. Work and school have occupied me a whole bunch.
